name: reviewdog (Actionlint)
on:
  pull_request:
    paths:
      - '.github/workflows/**.yml'
      - '.github/workflows/**.yaml'

jobs:
  actionlint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: リポジトリをチェックアウト (Checkout repository)
        uses: actions/checkout@v4

      - name: actionlintでワークフローを検査 (Lint workflows with actionlint)
        uses: reviewdog/action-actionlint@v1.65.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review 