name: Secretlint (変更ファイルのみ) # ワークフロー名

on:
  push: # プッシュイベントでトリガー
  pull_request: # プルリクエストイベントでトリガー

jobs:
  secretlint-check: # ジョブ名
    name: "変更ファイルのみシークレット検査" # 表示名
    runs-on: ubuntu-24.04 # 実行環境

    permissions:
      contents: read # リポジトリの内容を読み取る権限

    steps:
      - name: リポジトリをチェックアウト # ステップ名
        uses: actions/checkout@v4 # リポジトリをワークフローにチェックアウト

      - name: 変更ファイルを取得 # ステップ名
        id: get-diff
        uses: technote-space/get-diff-action@v6 # 変更ファイルを取得するアクション

      - name: Node.jsをセットアップ # ステップ名
        uses: actions/setup-node@v4 # Node.jsをセットアップするアクション
        with:
          node-version: 16 # 使用するNode.jsのバージョン

      - name: 依存関係をインストール # ステップ名
        run: npm install # npm依存関係をインストール

      - name: Secretlintで検査 # ステップ名
        # 変更されたファイルがある場合のみsecretlintを実行
        if: ${{ steps.get-diff.outputs.diff != '' }}
        run: npx --no-install secretlint ${{ steps.get-diff.outputs.diff }} # 変更されたファイルに対してsecretlintを実行
